const navData = [
  { id: 'ai-search', name: 'Ai搜索' },
  { id: 'social', name: '社交媒体' },
  { id: 'tools', name: '实用工具' },
  { id: 'tech-news', name: '科技资讯' },
  { id: 'cloud-storage', name: '云存储' },
  { id: 'email', name: '电子邮箱' }
];

const linkData = {
  'ai-search': [
    { url: 'https://www.google.com', icon: 'fa-brands fa-google', name: 'Google' },
    { url: 'https://unlimitedai.chat/', icon: 'fa-solid fa-pepper-hot', name: '无限制AI' },
    { url: 'https://openrouter.ai/', icon: 'fa-brands fa-openid', name: 'openrouter' },
    { url: 'https://websim.ai/', icon: 'fa-solid fa-magnifying-glass', name: 'websim' },
    { url: 'https://chatgpt.com/', icon: 'fa-brands fa-google', name: 'chatgpt' },
    { url: 'https://www.doubao.com/chat/', icon: 'fa-solid fa-paw', name: '傻豆包' },
    { url: 'https://space.coze.cn/', icon: 'fa-solid fa-shuttle-space', name: '扣子空间' },
    { url: 'https://chat.qwen.ai/', icon: 'fa-brands fa-rocketchat', name: '通义千问' },
    { url: 'https://kimi.moonshot.cn/', icon: 'fa-regular fa-moon', name: 'kimi' },
    { url: 'https://yiyan.baidu.com/', icon: 'fa-solid fa-dumpster-fire', name: '文心一言' },
    { url: 'https://yuanbao.tencent.com/', icon: 'fa-solid fa-robot', name: '腾讯元宝' },
    { url: 'https://www.minimax.io/', icon: 'fa-solid fa-minimize', name: 'minimax' },
    { url: 'https://chat.z.ai/', icon: 'fa-solid fa-z', name: 'z.ai' },
    { url: 'https://aistudio.google.com/', icon: 'fa-solid fa-robot', name: 'google AIstudio' },
    { url: 'https://gemini.google.com/', icon: 'fa-brands fa-google-plus', name: 'gemini' },
    { url: 'https://labs.google/fx/zh', icon: 'fa-brands fa-google-plus', name: 'labs.google' },
    { url: 'https://jules.google.com/', icon: 'fa-brands fa-google-plus', name: 'jules.google' },
    { url: 'https://copilot.microsoft.com/', icon: 'fa-brands fa-windows', name: 'copilot' },
    { url: 'https://build.nvidia.com/', icon: 'fa-solid fa-microchip', name: 'nvidia' },
    { url: 'https://claude.ai/', icon: 'fa-solid fa-robot', name: 'claude' },
    { url: 'https://chat.chutes.ai/', icon: 'fa-solid fa-robot', name: 'chutesai' },
    { url: 'https://mistral.ai/', icon: 'fa-solid fa-brain', name: 'mistral' },
    { url: 'https://groq.com/', icon: 'fa-solid fa-group-arrows-rotate', name: 'groq' },
    { url: 'https://www.medscape.com/', icon: 'fa-solid fa-stethoscope', name: 'medscape' },
    { url: 'https://heck.ai/', icon: 'fa-brands fa-rocketchat', name: 'heck.ai' },
    { url: 'https://www.wenxiaobai.com/', icon: 'fa-solid fa-mask', name: '问小白' },
    { url: 'https://app.leonardo.ai/', icon: 'fa-regular fa-images', name: 'leonardo.ai绘图' },
    { url: 'https://huggingface.co/', icon: 'fa-solid fa-face-rolling-eyes', name: 'huggingface' },
    { url: 'https://lmarena.ai/', icon: 'fa-solid fa-robot', name: 'lmarena' },
    { url: 'https://anyrouter.top/', icon: 'fa-solid fa-robot', name: 'anyrouter' },
    { url: 'https://x.ai/', icon: 'fa-brands fa-x-twitter', name: 'x.ai' },
    { url: 'https://ascvdpce.186404.xyz/', icon: 'fa-solid fa-heart-pulse', name: 'pce计算' },
    { url: 'https://t3.chat/', icon: 'fa-brands fa-rocketchat', name: 't3.chat' },
    { url: 'https://v0.dev/', icon: 'fa-solid fa-v', name: 'v0' },
    { url: 'https://www.deepseek.com/', icon: 'fa-brands fa-rocketchat', name: 'deepseek' },
    { url: 'https://ai.dangbei.com/', icon: 'fa-brands fa-rocketchat', name: '当贝AI' },
    { url: 'https://www.genspark.ai/', icon: 'fa-brands fa-rocketchat', name: 'genspark.ai' },
    { url: 'https://firebase.google.com/', icon: 'fa-solid fa-code-branch', name: 'firebase.google' },
    { url: 'https://kiro.dev/', icon: 'fa-brands fa-rocketchat', name: 'kiro.dev' },
    { url: 'https://sigmabrowser.com/chat', icon: 'fa-brands fa-rocketchat', name: 'sigmachat' },
    { url: 'https://siliconflow.cn/', icon: 'fa-brands fa-confluence', name: '硅基流动' },
    { url: 'https://www.modelscope.cn/', icon: 'fa-solid fa-code-branch', name: '魔塔社区' },
    { url: 'https://readdy.ai/', icon: 'fa-solid fa-bolt', name: 'readdy' },
    { url: 'https://bolt.new/', icon: 'fa-solid fa-bolt', name: 'bolt.new' }
  ],
  'social': [
    { url: 'https://www.facebook.com', icon: 'fa-brands fa-facebook', name: 'Facebook' },
    { url: 'https://x.com/', icon: 'fa-brands fa-twitter', name: 'Twitter' },
    { url: 'https://twitterxz.com/', icon: 'fa-brands fa-x-twitter', name: '推特视频下载' },
    { url: 'https://www.instagram.com', icon: 'fa-brands fa-instagram', name: 'Instagram' },
    { url: 'https://render.com/', icon: 'fa-solid fa-draw-polygon', name: 'render' },
    { url: 'https://deno.com/deploy', icon: 'fa-solid fa-d', name: 'deno' },
    { url: 'https://railway.com/', icon: 'fa-solid fa-archway', name: 'railway' },
    { url: 'https://vercel.com/', icon: 'fa-solid fa-v', name: 'vercel' },
    { url: 'https://www.netlify.com/', icon: 'fa-brands fa-n', name: 'netlify' },
    { url: 'https://zh.savefrom.net/', icon: 'fa-solid fa-share-from-square', name: 'savefrom' },
    { url: 'https://goingbus.com/', icon: 'fa-brands fa-n', name: '爆米花视频' },
    { url: 'https://www.reddit.com', icon: 'fa-brands fa-reddit', name: 'Reddit' },
    { url: 'https://www.downloadyoutubesubtitles.com/', icon: 'fa-brands fa-youtube', name: '油管字幕下载' },
    { url: 'https://github.com/', icon: 'fa-brands fa-github', name: 'GitHub' },
    { url: 'https://www.y2mate.com/', icon: 'fa-solid fa-download', name: '油管视频下载' },
    { url: 'https://youtube.iiilab.com/', icon: 'fa-solid fa-download', name: '视频下载' },
    { url: 'https://suno.com/', icon: 'fa-solid fa-music', name: 'suno' },
    { url: 'https://mv.186404.xyz/', icon: 'fa-solid fa-tv', name: '电影导航' }
  ],
  'tools': [
    { url: 'https://translate.google.com', icon: 'fa-solid fa-language', name: 'Google翻译' },
    { url: 'https://d.186404.xyz/', icon: 'fa-solid fa-link', name: '短链' },
    { url: 'https://dynv6.com/', icon: 'fa-solid fa-network-wired', name: 'dynv6' },
    { url: 'https://fast.com/', icon: 'fa-solid fa-gauge-high', name: '网速测试' },
    { url: 'https://www.cloudns.net/', icon: 'fa-solid fa-cloud', name: 'Cloudns' },
    { url: 'https://www.cloudflare.com/zh-cn/', icon: 'fa-solid fa-shield-halved', name: 'Cloudflare' },
    { url: 'https://ygpy.net/', icon: 'fa-solid fa-user-group', name: '一个朋友' },
    { url: 'https://notebooklm.google/', icon: 'fa-solid fa-book', name: '谷歌笔记' },
    { url: 'https://email.ml/', icon: 'fa-solid fa-envelope', name: '临时邮箱' },
    { url: 'https://www.ahhhhfs.com/', icon: 'fa-solid fa-blog', name: 'A姐' },
    { url: 'https://ip.sb/', icon: 'fa-solid fa-location-dot', name: 'IP查询' },
    { url: 'https://dns.he.net/', icon: 'fa-solid fa-network-wired', name: 'dns.he域名托管' },
    { url: 'https://www.site.ac/', icon: 'fa-solid fa-right-left', name: 'Site域名转发' },
    { url: 'https://zh.go-to-library.sk/', icon: 'fa-solid fa-book-reader', name: 'Z-Library' },
    { url: 'https://domain.digitalplat.org/', icon: 'fa-solid fa-globe', name: 'us.kg域名' },
    { url: 'https://www.spaceship.com/zh/', icon: 'fa-solid fa-rocket', name: 'Spaceship廉价域名' },
    { url: 'https://www.cursor.com/', icon: 'fa-solid fa-i-cursor', name: 'cursor' },
    { url: 'https://fontawesome.com/', icon: 'fa-solid fa-icons', name: 'FontAwesome图标' },
    { url: 'https://scamalytics.com/', icon: 'fa-solid fa-icons', name: 'ip清洁度查询' },
    { url: 'https://test-ipv6.com/', icon: 'fa-solid fa-ethernet', name: 'test-ipv6' },
    { url: 'https://html.zone/ip', icon: 'fa-brands fa-sourcetree', name: 'zone/ip' },
    { url: 'https://www.lumiproxy.com/zh-hans/online-proxy/proxysite/', icon: 'fa-solid fa-unlock', name: '免费网络代理' },
    { url: 'https://ipcheck.ing/', icon: 'fa-solid fa-location-dot', name: 'ipcheck' },
    { url: 'https://console.cron-job.org/', icon: 'fa-solid fa-ethernet', name: '定时任务cron-job' },
    { url: 'https://uptimerobot.com/', icon: 'fa-solid fa-location-dot', name: 'uptimerobot' },
    { url: 'https://forwardemail.net/', icon: 'fa-solid fa-envelopes-bulk', name: 'forwardemail' },
    { url: 'https://improvmx.com/', icon: 'fa-solid fa-envelopes-bulk', name: 'improvmx' },
    { url: 'https://gb.w404.nyc.mn/', icon: 'fa-brands fa-github', name: 'github文件加速' },
    { url: 'https://hostry.com/', icon: 'fa-solid fa-clock-rotate-left', name: 'hostryDNS域名托管' },
    { url: 'https://www.sitelutions.com/', icon: 'fa-solid fa-sitemap', name: '免费域名sitelutions' },
    { url: 'https://www.changeip.com/', icon: 'fa-solid fa-satellite-dish', name: '免费域名changeip' },
    { url: 'https://dnsexit.com/', icon: 'fa-solid fa-users', name: '免费域名dnsexit' },
    { url: 'https://www.gname.vip/', icon: 'fa-solid fa-users', name: '免费域名gname' },
    { url: 'https://www.nslookup.io/', icon: 'fa-solid fa-arrows-rotate', name: 'DNS查找nslookup' },
    { url: 'https://ping0.cc/', icon: 'fa-solid fa-fingerprint', name: 'ping0' },
    { url: 'https://customer.l53.net/', icon: 'fa-solid fa-fingerprint', name: 'L53免费域名' },
    { url: 'https://tools.pdf24.org/', icon: 'fa-solid fa-file-pdf', name: 'PDF在线工具' },
    { url: 'http://free-proxy.cz/en/', icon: 'fa-brands fa-internet-explorer', name: 'free-proxy' },
    { url: 'https://www.croxyproxy.rocks/_zh/', icon: 'fa-solid fa-unlock', name: '在线代理croxyproxy' },
    { url: 'https://doocs.github.io/md/', icon: 'fa-regular fa-edit', name: '微信Markdown编辑器' },
    { url: 'https://www.proxysite.com/', icon: 'fa-solid fa-unlock', name: 'proxysite' },
    { url: 'https://www.serv00.com/', icon: 'fa-solid fa-server', name: 'serv00' },
    { url: 'https://www.hostuno.com/', icon: 'fa-solid fa-server', name: 'hostuno' },
    { url: 'https://github.com/Molunerfinn/PicGo', icon: 'fa-solid fa-cloud-arrow-up', name: 'PicGo' },
    { url: 'https://smms.app/', icon: 'fa-solid fa-image', name: 'SM.MS' },
    { url: 'https://freeimage.host/', icon: 'fa-solid fa-photo-film', name: 'FreeImageHost' },
    { url: 'https://cobalt.tools/', icon: 'fa-brands fa-youtube', name: 'cobalt' },
    { url: 'https://codeium.com/', icon: 'fa-solid fa-code', name: 'Windsurf' },
    { url: 'https://tinywow.com/', icon: 'fa-brands fa-free-code-camp', name: 'tinywow' },
    { url: 'https://paywallbuster.com/', icon: 'fa-solid fa-key', name: '付费墙' },
    { url: 'https://g.186404.xyz/wallHub/', icon: 'fa-solid fa-unlock', name: 'PaywallHub' },
    { url: 'https://fmhy.net/', icon: 'fa-regular fa-folder-open', name: 'fmhy' },
    { url: 'https://www.remove.bg/', icon: 'fa-solid fa-image-portrait', name: 'remove' },
    { url: 'https://picwish.com/', icon: 'fa-regular fa-image', name: 'picwish' },
    { url: 'https://zenvideo.qq.com/', icon: 'fa-solid fa-video', name: '腾讯智影' },
    { url: 'https://www.hidoha.net/', icon: 'fa-solid fa-fingerprint', name: '免费域名HiDNS' },
    { url: 'https://pixabay.com/', icon: 'fa-brands fa-pix', name: 'pixabay' },
    { url: 'https://www.infinityfree.com/', icon: 'fa-solid fa-infinity', name: 'InfinityFree' },
    { url: 'https://anyvoice.net/', icon: 'fa-solid fa-microphone', name: 'anyvoice' },
    { url: 'https://fish.audio/', icon: 'fa-solid fa-fish', name: 'fish.audio' },
    { url: 'https://noiz.ai/', icon: 'fa-solid fa-circle-notch', name: 'noizai' },
    { url: 'https://hailuoai.video/', icon: 'fa-solid fa-file-audio', name: '海螺Ai' },
    { url: 'https://desec.io/', icon: 'fa-solid fa-anchor', name: 'desec免费域名' },
    { url: 'https://lovable.dev/', icon: 'fa-solid fa-shield-heart', name: 'lovable网站生成' },
    { url: 'https://www.netlib.re/', icon: 'fa-solid fa-globe', name: 'netlib免费域名' },
    { url: 'https://zone.id/', icon: 'fa-solid fa-id-card-clip', name: 'zone免费域名' },
    { url: 'https://x10hosting.com/', icon: 'fa-solid fa-ghost', name: 'x10hosting免费托管' },
    { url: 'https://www.nodeloc.com/', icon: 'fa-brands fa-hashnode', name: 'nodeloc社区' },
    { url: 'https://same.new/', icon: 'fa-solid fa-copy', name: 'same复制网站' },
    { url: 'https://claw.cloud/', icon: 'fa-solid fa-cloud', name: 'claw容器' },
    { url: 'https://www.subeasy.ai/zh-CN', icon: 'fa-solid fa-closed-captioning', name: 'subeasy字幕' },
    { url: 'https://cardify.godsbee.com/', icon: 'fa-solid fa-credit-card', name: '知识卡片' },
    { url: 'https://www.webhostmost.com/', icon: 'fa-solid fa-web-awesome', name: 'webhostmost网站托管' },
    { url: 'https://edgeone.ai/', icon: 'fa-solid fa-dice-one', name: '腾讯edgeone' },
    { url: 'https://www.stormkit.io/', icon: 'fa-solid fa-cloud', name: 'Stormkit' }
  ],
  'tech-news': [
    { url: 'https://www.techcrunch.com', icon: 'fa-solid fa-newspaper', name: 'TechCrunch' },
    { url: 'https://www.wired.com', icon: 'fa-solid fa-bolt', name: 'Wired' },
    { url: 'https://www.theverge.com', icon: 'fa-solid fa-laptop', name: 'The Verge' },
    { url: 'https://arstechnica.com', icon: 'fa-solid fa-rocket', name: 'Ars Technica' },
    { url: 'https://www.engadget.com', icon: 'fa-solid fa-mobile-screen', name: 'Engadget' },
    { url: 'https://scitechdaily.com/', icon: 'fa-solid fa-microscope', name: '科技日报' },
    { url: 'https://techradar.com', icon: 'fa-solid fa-satellite', name: 'TechRadar' },
    { url: 'https://b.186404.xyz/', icon: 'fa-solid fa-blog', name: '科技博客' },
    { url: 'https://www.cnbeta.com.tw/', icon: 'fa-solid fa-circle-info', name: 'cnbeta' }
  ],
  'cloud-storage': [
    { url: 'https://www.dropbox.com', icon: 'fa-brands fa-dropbox', name: 'Dropbox' },
    { url: 'https://drive.google.com', icon: 'fa-brands fa-google-drive', name: 'Google Drive' },
    { url: 'https://onedrive.live.com', icon: 'fa-brands fa-microsoft', name: 'OneDrive' },
    { url: 'https://www.box.com', icon: 'fa-solid fa-box', name: 'Box' },
    { url: 'https://www.mediafire.com', icon: 'fa-solid fa-file', name: 'MediaFire' },
    { url: 'https://mega.nz', icon: 'fa-solid fa-cloud-arrow-up', name: 'MEGA' },
    { url: 'https://mypikpak.com/', icon: 'fa-solid fa-cloud', name: 'PikPak' }
  ],
  'email': [
    { url: 'https://mail.google.com', icon: 'fa-solid fa-envelope', name: 'Gmail' },
    { url: 'https://outlook.live.com', icon: 'fa-brands fa-microsoft', name: 'Outlook' },
    { url: 'https://cock.li/', icon: 'fa-solid fa-envelope-open', name: 'cock邮箱' },
    { url: 'https://disroot.org/', icon: 'fa-solid fa-envelope-circle-check', name: 'disroot邮箱' },
    { url: 'https://www.protonmail.com', icon: 'fa-solid fa-shield-halved', name: 'ProtonMail' },
    { url: 'https://mail.qq.com', icon: 'fa-brands fa-qq', name: 'QQ邮箱' },
    { url: 'https://librem.one/', icon: 'fa-solid fa-at', name: 'librem邮箱' },
    { url: 'https://www.linshigmail.com/', icon: 'fa-solid fa-envelopes-bulk', name: '临时谷歌邮箱' }
  ]
};